import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/copmonents/navbar";
import StoreProvider from "@/redux/store";
import localFont from "next/font/local"
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontVazir = localFont({
  src : "../public/Vazirmatn[wght].woff2"
})

function RootLayout({children}: Readonly<{children: React.ReactNode;}>){
  return (
    <html lang="en" dir="rtl" suppressHydrationWarning>
      <body className={`${fontVazir.className}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <StoreProvider>
            <Navbar/>
            {children}
          </StoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

export default RootLayout
