import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/copmonents/navbar";
import StoreProvider from "@/redux/store";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body>
        <StoreProvider>
          <Navbar/>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
